### PR TITLE
Hotfix: replace old date to actual in config

### PR DESCRIPTION
**Pull request by EncryptEx**
The value changed enables the mentorship applications to be open,

## Some questions
- [x] I have read the contributing guidelines
- [x] I abide by this repository Code of Conduct
- [x] I understand that my PR won't be merged until GitHub gives a "green light"

### CODE REVIEW

**Review by jmiarons — APPROVED** [review]

**Review by aacraf — APPROVED** [review]
ok

**Review by Casassarnau — DISMISSED** [review]
Com que 2024? xd

**Comment by jmiarons** [comment]
es un entorn de test es igual la data xd

**Comment by Casassarnau** [comment]
> es un entorn de test es igual la data xd

No ho es, si es fa merge s'acabara ficant al de producció

**Comment by EncryptEx** [comment]
> Com que 2024? xd

typo sorry

**Pull request merged**
